# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cluely < Formula
  desc "CLI for the Cluely platform"
  homepage "https://cluely.com"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cluely/cluely-cli/releases/download/v0.1.0/cluely_0.1.0_darwin_amd64.tar.gz"
      sha256 "e54e31168776fa26db4bb335138c34baaeb6bbfc184602b081079dda71c108ba"

      define_method(:install) do
        bin.install "cluely"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cluely/cluely-cli/releases/download/v0.1.0/cluely_0.1.0_darwin_arm64.tar.gz"
      sha256 "a6ce051deba918768d53a669d9e1810c5d3073a8fa26a4c94514ef1ed9206128"

      define_method(:install) do
        bin.install "cluely"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cluely/cluely-cli/releases/download/v0.1.0/cluely_0.1.0_linux_amd64.tar.gz"
      sha256 "95de9b4ba46c1be4bddc18b259b4133c549740f9920f43d191ec71da4ef97348"
      define_method(:install) do
        bin.install "cluely"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cluely/cluely-cli/releases/download/v0.1.0/cluely_0.1.0_linux_arm64.tar.gz"
      sha256 "a845f1aedbf51551168db4066ba66156607155f14f94d2bcad312599e3bce991"
      define_method(:install) do
        bin.install "cluely"
      end
    end
  end

  test do
    system "#{bin}/cluely", "--version"
  end
end
