# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cluely < Formula
  desc "CLI for the Cluely platform"
  homepage "https://cluely.com"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cluely/cluely-cli/releases/download/v0.1.2/cluely_0.1.2_darwin_amd64.tar.gz"
      sha256 "ab77f79704d0fc0626613f27bc1d1ad0f43e952e31140e52c2d323d6744217bd"

      define_method(:install) do
        bin.install "cluely"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cluely/cluely-cli/releases/download/v0.1.2/cluely_0.1.2_darwin_arm64.tar.gz"
      sha256 "9a13847603ef15654887ad7c28868d34b65f83644f3f205d99ad7cce2b820a36"

      define_method(:install) do
        bin.install "cluely"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cluely/cluely-cli/releases/download/v0.1.2/cluely_0.1.2_linux_amd64.tar.gz"
      sha256 "c9b5ae7d0cc4ea2bb9f21d1dcb1e85d27716f363e69b1d050a54be13018e6e4e"
      define_method(:install) do
        bin.install "cluely"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cluely/cluely-cli/releases/download/v0.1.2/cluely_0.1.2_linux_arm64.tar.gz"
      sha256 "b14560bd3ffb7fcf61f43fb61baf14bfc4b3f069f17f433a09664adbaf57cc40"
      define_method(:install) do
        bin.install "cluely"
      end
    end
  end

  test do
    system "#{bin}/cluely", "--version"
  end
end
