# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cluely < Formula
  desc "CLI for the Cluely platform"
  homepage "https://cluely.com"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cluely/cluely-cli/releases/download/v0.1.3/cluely_0.1.3_darwin_amd64.tar.gz"
      sha256 "4cc8bd12ad2f34b9a04a9d1ef30e13463f3af5e9f3095674750a14666c2df5a6"

      define_method(:install) do
        bin.install "cluely"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cluely/cluely-cli/releases/download/v0.1.3/cluely_0.1.3_darwin_arm64.tar.gz"
      sha256 "114adbc2cf8b4c022fd9f86a619508e047ac9663ffbf4c185129ea49b70c1ff6"

      define_method(:install) do
        bin.install "cluely"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cluely/cluely-cli/releases/download/v0.1.3/cluely_0.1.3_linux_amd64.tar.gz"
      sha256 "4d520f5ce6643450fc86f6d388681b7ab6a0126f8adb2e4c655973e7988f3228"
      define_method(:install) do
        bin.install "cluely"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cluely/cluely-cli/releases/download/v0.1.3/cluely_0.1.3_linux_arm64.tar.gz"
      sha256 "93d9be0d2df692c6f0d58f04bb974f676adce77705b4fd7171df23423003a35c"
      define_method(:install) do
        bin.install "cluely"
      end
    end
  end

  test do
    system "#{bin}/cluely", "--version"
  end
end
